import discord
from datetime import datetime
from typing import List
from db.models import Commitment, CommitmentStatus, DiningInquiry
from llm.schemas import RestaurantRecommendations


def create_commitment_embed(commitment: Commitment, is_alert: bool = False) -> discord.Embed:
    """Creates a visually polished embed for a commitment or upcoming alert."""
    if is_alert:
        color = discord.Color.gold()
        title = "⏰ Commitment Radar Alert"
        desc = f"Hey <@{commitment.user_id}>, you made a promise that is due soon!"
    else:
        color = discord.Color.blurple()
        title = "🎯 Micro-Commitment Registered"
        desc = f"Tracked for <@{commitment.user_id}>"

    embed = discord.Embed(
        title=title,
        description=desc,
        color=color,
        timestamp=datetime.utcnow()
    )

    embed.add_field(name="📋 Task", value=f"**{commitment.task_title}**", inline=False)
    
    if commitment.recipient:
        embed.add_field(name="👤 For / Recipient", value=commitment.recipient, inline=True)
    
    # Format deadline as Discord relative timestamp
    deadline_ts = int(commitment.deadline_utc.timestamp())
    embed.add_field(
        name="⏳ Implied Deadline",
        value=f"<t:{deadline_ts}:R> (<t:{deadline_ts}:t>)",
        inline=True
    )
    
    if commitment.relative_deadline_text:
        embed.add_field(name="💬 Mentioned Timeframe", value=f'"{commitment.relative_deadline_text}"', inline=True)

    status_emojis = {
        CommitmentStatus.PENDING: "🟡 In Progress",
        CommitmentStatus.NOTIFIED: "🟠 Due Soon",
        CommitmentStatus.COMPLETED: "✅ Completed",
        CommitmentStatus.SNOOZED: "⏱️ Postponed",
        CommitmentStatus.CANCELLED: "❌ Cancelled"
    }
    status_str = status_emojis.get(commitment.status, str(commitment.status))
    embed.add_field(name="Status", value=status_str, inline=True)

    if commitment.context_snippet:
        embed.add_field(name="Context", value=commitment.context_snippet[:200], inline=False)

    embed.set_footer(text=f"Commitment Radar ID: #{commitment.id} • Click below to resolve or update")
    return embed


def create_commitments_list_embed(commitments: List[Commitment], user_name: str) -> discord.Embed:
    """Creates an overview embed listing all active commitments for a user."""
    embed = discord.Embed(
        title=f"🎯 Active Commitments for {user_name}",
        description="Here are the micro-commitments detected across your conversations:",
        color=discord.Color.blue(),
        timestamp=datetime.utcnow()
    )

    if not commitments:
        embed.description = "🎉 No open micro-commitments! You're completely caught up."
        return embed

    for c in commitments:
        deadline_ts = int(c.deadline_utc.timestamp())
        status_icon = "🟡" if c.status in [CommitmentStatus.PENDING, CommitmentStatus.NOTIFIED] else "✅"
        recipient_info = f" (for {c.recipient})" if c.recipient else ""
        
        embed.add_field(
            name=f"{status_icon} #{c.id}: {c.task_title}{recipient_info}",
            value=f"Due: <t:{deadline_ts}:R> | Originally: *\"{c.raw_text[:60]}...\"*",
            inline=False
        )

    embed.set_footer(text="Use the action buttons or /commitments resolve <id>")
    return embed


def create_resolution_embed(commitment: Commitment, action: str) -> discord.Embed:
    """Creates an embed confirming resolution or postponement."""
    embed = discord.Embed(
        title=f"✅ Commitment Updated: #{commitment.id}",
        description=f"**{commitment.task_title}** has been marked as **{action}**.",
        color=discord.Color.green(),
        timestamp=datetime.utcnow()
    )
    return embed


def create_dining_prompt_embed(inquiry: DiningInquiry, timeout_seconds: int = 15) -> discord.Embed:
    """Creates an engaging embed when a dining inquiry has gone unanswered."""
    embed = discord.Embed(
        title="🍽️ Dining Plan Deadlock Detected!",
        description=(
            f"Hey everyone! <@{inquiry.user_id}> asked:\n"
            f"> *\"{inquiry.raw_text}\"*\n\n"
            f"No one has chimed in for **{timeout_seconds} seconds**, so let's break the deadlock!\n"
            f"**What kind of food are you in the mood for?** Pick an option below:"
        ),
        color=discord.Color.orange(),
        timestamp=datetime.utcnow()
    )
    embed.set_footer(text=f"Inquiry ID: #{inquiry.id} • Ambient Dining Concierge")
    return embed


def create_restaurant_suggestions_embed(recs: RestaurantRecommendations) -> discord.Embed:
    """Creates a formatted card with restaurant options generated by Hermes."""
    location_str = f" in {recs.location}" if recs.location else ""
    embed = discord.Embed(
        title=f"🍴 Top {recs.cuisine} Spots{location_str}",
        description=f"{recs.summary}\nHere are top picks for the group:",
        color=discord.Color.teal(),
        timestamp=datetime.utcnow()
    )

    for i, opt in enumerate(recs.options, 1):
        price_badge = f"`{opt.price_range}`" if opt.price_range else ""
        vibe_str = f" • *{opt.vibe}*" if opt.vibe else ""
        header = f"{i}. 📍 **{opt.name}** {price_badge}{vibe_str}"
        
        details = []
        if opt.highlight_dish:
            details.append(f"⭐ **Must Try:** {opt.highlight_dish}")
        if opt.why_go:
            details.append(f"💡 {opt.why_go}")
        
        embed.add_field(
            name=header,
            value="\n".join(details) if details else opt.cuisine_type,
            inline=False
        )

    embed.set_footer(text="Pick a favorite or click 'More Options' to re-roll!")
    return embed


def create_already_accepted_plan_embed(
    user_id: str,
    agreed_plan: str,
    quote: Optional[str] = None,
    source: str = "earlier"
) -> discord.Embed:
    """Creates an embed reminding the channel that a dinner plan was already accepted."""
    embed = discord.Embed(
        title="💡 Dinner Plan Already Agreed Upon!",
        description=(
            f"Hey <@{user_id}>, a plan was already agreed on for dinner ({source}):\n\n"
            f"🍽️ **Confirmed Plan:** **{agreed_plan}**\n"
        ),
        color=discord.Color.green(),
        timestamp=datetime.utcnow()
    )
    if quote:
        embed.add_field(name="💬 Context", value=f"> *\"{quote[:250]}\"*", inline=False)

    embed.add_field(
        name="👉 Next Step",
        value="Do you want to **stick with this plan**, or **pick somewhere new**?",
        inline=False
    )
    embed.set_footer(text="Commitment Radar • Consensus Memory")
    return embed


def create_dining_loading_embed(cuisine_or_craving: str, location: str) -> discord.Embed:
    """Creates a visually distinct loading card while the Hermes AI backend API call is running."""
    embed = discord.Embed(
        title="🍳 AI Concierge is Cooking...",
        description=(
            f"📡 **Calling OpenRouter AI Backend (Hermes 3)...**\n\n"
            f"🍽️ **Target:** `{cuisine_or_craving}`\n"
            f"📍 **Location:** `{location}`\n\n"
            f"⏳ *Scouting top-rated spots, signature dishes, price tiers, and vibes...*"
        ),
        color=discord.Color.gold(),
        timestamp=datetime.utcnow()
    )
    embed.set_footer(text="OpenRouter API in progress • Please hold on a moment...")
    return embed

